version: '3.9'

services:
  postgres:
    image: postgres:16
    container_name: universe-postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: planets_db
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./docker/init-db.sql:/docker-entrypoint-initdb.d/init-db.sql #chạy file sql khi khởi động container
  pgadmin:
    image: dpage/pgadmin4
    container_name: universe-pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@gmail.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - '5050:80'
volumes:
  postgres_data:
